[package]
name = "calc-rs_gui"
version = "0.1.0"
authors = ["Christofer Reinholdsson <christofer.reinholdsson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calc-rs_core = { path = "../calc-rs_core" }